sudo apt install speedtest-cli;
echo "Speed before limiter";
speedtest-cli;
cd /bin;
git clone https://github.com/magnific0/wondershaper.git;
cd wondershaper;
sudo make install;
sudo systemctl enable wondershaper.service;
echo "Enter inbound limit (Ex:- 30Mbps = 30000)";
read inbound;
echo "Enter outbound limit (Ex:- 30Mbps = 30000)";
read outbound;
sudo wondershaper -a eth0 -d $inbound -u $outbound ;
sudo systemctl start wondershaper.service;
sudo systemctl status wondershaper.service;
echo "Speed after limiter";
speedtest-cli;
