version: "1"

services:
  rtmp:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped